---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
    - name: tutum-hello-world
      image: tutum/hello-world
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
    - name: "30000"
      port: 30000
      targetPort: 80
  selector:
    app: hello-world
