---
apiVersion: v1
kind: Pod
metadata:
  name: one-pod
  labels:
    app: one-pod
spec:
  restartPolicy: Always
  containers:
    - name: one-container
      image: busybox:latest
      command: ["sleep"]
      args: ["1000"]